name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Replace with your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js (optional, if you have a build step)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Replace with your required Node.js version

      # Step 3: Install dependencies (optional)
      - name: Install dependencies
        run: npm install

      # Step 4: Build the project (optional)
      - name: Build the project
        run: npm run build

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Replace with the directory containing the built site files
